version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: commander
        versions:
          - ">=15"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
